version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: document_processing_db
    environment:
      POSTGRES_DB: document_processing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - document_processing
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: document_processing_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - document_processing
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # LocalStack for simulating AWS services
  localstack:
    image: localstack/localstack:latest
    container_name: document_processing_localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,lambda,stepfunctions,iam,logs,events
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./scripts/localstack:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - localstack_data:/tmp/localstack
    networks:
      - document_processing

  # API Development
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: document_processing_api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=document_processing
      - REDIS_HOST=redis
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - document_processing

volumes:
  postgres_data:
  redis_data:
  localstack_data:

networks:
  document_processing:
    driver: bridge
